name: CI/CD Pipeline

on:
  push:
    branches:
      - develop  # Bilo koji push na develop grani pokreće pipeline

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repozitorijuma
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instalacija zavisnosti i build
      - name: Install dependencies and build Backend
        run: |
          cd backend
          git pull origin develop
          sudo pip install --ignore-installed -r requirements.txt
          sudo systemctl restart fastapi

      - name: Install dependencies and build Frontend
        run: |
          cd frontend/app
          git pull origin develop
          npm install
          npm run build
          sudo rm -rf /var/www/frontend/*
          sudo cp -r dist/* /var/www/frontend/
          sudo systemctl restart nginx
