name: CI/CD Pipeline

on:
  push:
    branches:
      - develop  # Bilo koji push na develop grani pokreće pipeline

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repozitorijuma
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instalacija zavisnosti i build Backenda
      - name: Install dependencies and build Backend
        run: |
          cd backend
          git pull origin develop
          sudo pip install --ignore-installed -r requirements.txt
          
      # 3. Restartovanje FastAPI servisa na VM-u putem SSH
      - name: Restart FastAPI service on VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.YC_VM_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart fastapi.service

      # 4. Instalacija zavisnosti i build Frontenda
      - name: Install dependencies and build Frontend
        run: |
          cd frontend/app
          git pull origin develop
          npm install
          npm run build
          sudo rm -rf /var/www/frontend/*
       
      # 5. Kreiranje direktorijuma ako ne postoji i kopiranje dist fajlova
      - name: Copy dist files to frontend directory
        run: |
          sudo mkdir -p /var/www/frontend
          sudo cp -r dist/* /var/www/frontend/

      # 5. Restartovanje nginx servisa na VM-u putem SSH
      - name: Restart nginx service on VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.YC_VM_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart nginx
